### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by razielt10** [stupidusername/bukmark#1]
First: i clone the project bukmark
Second: in the directory /web/ i created a yii framework using composer, i was used:
   composer global require "fxp/composer-asset-plugin:~1.0.0" and 
   composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic

¿Need to configure a virtual host?
 
Thanks

**Comment by stupidusername** [comment]
The README contains instructions for installing a basic app template of Yii2. If you want to run this app you need to install the composer asset plugin:
`$ composer global require "fxp/composer-asset-plugin:^1.3.1"`
Clone the repo and then install its composer requirements:
`$ cd <app_path>`
`$ composer install`
Then you need to run the migrations in order to create the DB.
'$ ./yii migrate'

You can refer to the official Yii2 documentation for setting up a web server.
[http://www.yiiframework.com/doc-2.0/guide-start-installation.html](Installing Yii)

**Comment by niuwle** [comment]
Hi! I installed this but the links for the menu aren't working, what I'm missing, did all the steps for configuring. Here is my test env http://www.bukmark3.hobs.com.ar/

**Comment by stupidusername** [comment]
It looks like the web server it's not forwarding the request to the index.php script. Check out the official instalation guide of Yii2 and take a look on how to configure your web server.

[Installing Yii2](https://www.yiiframework.com/doc/guide/2.0/en/start-installation)
